services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb_alone
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    ports:
      - "3307:3307"
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data: